{% set name = "lenses" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ingolemo/python-{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 502e20c21e8f70dbc7c5abd89480a98f3373a732110d05cccaa5710ef7cb8328

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python>=3.6,<3.10
    - dataclasses # [py36]

test:
  imports:
    - lenses
  requires:
    - pytest
    - pytest-sugar
    - coverage
    - pytest-cov
    - hypothesis
    - mypy
    - pyrsistent
  source_files:
    - tests
  commands:
    - pytest .

about:
  home: https://github.com/ingolemo/python-lenses
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: A lens library for Python

  # The remaining entries in this section are optional, but recommended.
  description: |
    lenses is a python library that helps you to manipulate large
    data-structures without mutating them. It is inspired by the
    lenses in Haskell, although it's much less principled and the
    api is more suitable for Python.
  doc_url: https://python-lenses.readthedocs.io/
  dev_url: https://github.com/ingolemo/python-lenses

extra:
  recipe-maintainers:
    - lambiase
